{{- if .Values.dash.ingress.enabled -}}
apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
  name: "dash"
  annotations: {{ toYaml .Values.dash.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "dash"
    suite: "pachyderm"
spec:
  tls:
  - secretName: "dash-tls"
  rules:
    - host: {{ required "dash.ingress.host is required when dash.ingress.enabled" .Values.dash.ingress.host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "dash"
              servicePort: "dash-http"
          - path: "/ws"
            backend:
              serviceName: "dash"
              servicePort: "grpc-proxy-http"
{{ end -}}
