{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pachd
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      annotations:
        checksum/storage-secret: {{ include (print $.Template.BasePath "/pachd/storage-secret.yaml") . | sha256sum }}
        {{- if .Values.pachd.storage.amazon.iamRole }}
        iam.amazonaws.com/role: {{ .Values.pachd.storage.amazon.iamRole }}
        {{- end }}
      labels:
        app: pachd
        suite: pachyderm
      name: pachd
      namespace: {{ .Release.Namespace }}
    spec:
      containers:
      - command:
        - /pachd
        env:
        - name: LOKI_LOGGING
          value: {{ .Values.pachd.lokiLogging | quote}}
        - name: PACH_ROOT
          value: "/pach"
        - name: ETCD_PREFIX
          #value:
        - name: NUM_SHARDS
          value: {{ required ".Values.pachd.numShards is required." .Values.pachd.numShards | quote }}
        - name: STORAGE_BACKEND
          value: {{ required ".Values.pachd.storage.backend is required." .Values.pachd.storage.backend | quote }}
        - name: STORAGE_HOST_PATH
          {{- if eq .Values.pachd.storage.backend "LOCAL" }}
          value: {{ .Values.pachd.storage.local.hostPath }}pachd
          {{- end }}
        - name: WORKER_IMAGE
          value: "{{ .Values.worker.image.repository }}:{{ .Values.pachd.image.tag }}"
        - name: IMAGE_PULL_SECRET
          value: {{ .Values.imagePullSecret | quote }}
        - name: WORKER_SIDECAR_IMAGE
          value: "{{ .Values.pachd.image.repository }}:{{ .Values.pachd.image.tag }}"
        - name: WORKER_IMAGE_PULL_POLICY
          value: {{ .Values.worker.image.pullPolicy | quote }}
        - name: WORKER_SERVICE_ACCOUNT
          value: {{ .Values.worker.serviceAccount.name | quote }}
        - name: PACHD_VERSION
          value: "{{ .Values.pachd.image.tag }}"
        - name: METRICS
          value: {{ .Values.pachd.metrics.enabled | quote }}
        {{- if and .Values.pachd.goMaxProcs (gt .Values.pachd.goMaxProcs 0.0)}}
        - name: GOMAXPROCS
          value: {{ .Values.pachd.goMaxProcs | quote }}
        {{- end }}
        {{- if .Values.pachd.metricsEndpoint}}
        - name: METRICS_ENDPOINT
          value: "{{ .Values.pachd.metricsEndpoint }}"
        {{- end }}
        - name: LOG_LEVEL
          value: {{ .Values.pachd.logLevel }}
        - name: BLOCK_CACHE_BYTES
          value: {{ .Values.pachd.blockCacheBytes | quote }}
          {{- if.Values.pachd.storage.amazon.iamRole }}
        - name: IAM_ROLE
          value: {{ .Values.pachd.storage.amazon.iamRole | quote }}
          {{- end }}
        - name: NO_EXPOSE_DOCKER_SOCKET
          value: {{ .Values.pachd.exposeDockerSocket | not | quote }}
        - name: PACHYDERM_AUTHENTICATION_DISABLED_FOR_TESTING
          value: {{ .Values.pachd.authenticationDisabledForTesting | quote }}
        - name: PACH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PACHD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: pachd
              divisor: "0"
              resource: requests.memory
        - name: EXPOSE_OBJECT_API
          value: {{ .Values.pachd.exposeObjectAPI | quote }}
        {{- if .Values.pachd.clusterDeploymentID }}
        - name: CLUSTER_DEPLOYMENT_ID
          value: {{ .Values.pachd.clusterDeploymentID | quote }}
        {{- end }}
        - name: REQUIRE_CRITICAL_SERVERS_ONLY
          value: {{ .Values.pachd.requireCriticalServersOnly | quote }}
        - name: PACHD_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: PPS_WORKER_GRPC_PORT
          value: {{ .Values.pachd.ppsWorkerGRPCPort | quote }}
        - name: STORAGE_UPLOAD_CONCURRENCY_LIMIT
          value: {{ .Values.pachd.storage.uploadConcurrencyLimit | quote }}
        - name: STORAGE_PUT_FILE_CONCURRENCY_LIMIT
          value: {{ .Values.pachd.storage.putFileConcurrencyLimit | quote }}
        - name: STORAGE_V2
          value: "false"
        envFrom:
          - secretRef:
              name: pachyderm-storage-secret
        image: "{{ .Values.pachd.image.repository }}:{{ .Values.pachd.image.tag }}"
        imagePullPolicy: {{ .Values.pachd.image.pullPolicy }}
        {{- if .Values.imagePullSecret }}
        imagePullSecret: {{ .Values.imagePullSecret | quote }}
        {{- end }}
        name: pachd
        ports:
        - containerPort: 600
          name: s3gateway-port
          protocol: TCP
        - containerPort: 650
          name: api-grpc-port
          protocol: TCP
        - containerPort: 651
          name: trace-port
        - containerPort: 652
          name: api-http-port
          protocol: TCP
        - containerPort: 653
          name: peer-port
          protocol: TCP
        - containerPort: 655
          name: api-git-port
          protocol: TCP
        - containerPort: 654
          name: saml-port
          protocol: TCP
        - containerPort: 657
          name: oidc-port
          protocol: TCP
        - containerPort: 656
          name: prom-metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /pachd
            - --readiness
        {{- if .Values.pachd.resources }}
        resources: {{ toYaml .Values.pachd.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /pach
          name: pach-disk
        - mountPath: /pachyderm-storage-secret
          name: pachyderm-storage-secret
        {{- if .Values.pachd.tls.enabled }}
        - mountPath: /pachd-tls-cert
          name: pachd-tls-cert
        {{- end }}
      {{- if .Values.pachd.serviceAccount.name }}
      serviceAccountName: {{ .Values.pachd.serviceAccount.name | quote }}
      {{- end }}
      volumes:
      - name: pach-disk
        {{- if eq .Values.pachd.storage.backend "LOCAL" }}
        hostPath:
          path: {{ .Values.pachd.storage.local.hostPath }}pachd
          type: DirectoryOrCreate
        {{- end }}
      - name: pachyderm-storage-secret
        secret:
          secretName: pachyderm-storage-secret
      {{- if .Values.pachd.tls.enabled }}
      - name: pachd-tls-cert
        secret:
          secretName: {{ required "If pachd.tls.enabled, you must set pachd.tls.secretName" .Values.pachd.tls.secretName | quote }}
      {{- end }}
